# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kriat/bugtracker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "preview"

nameOverride: ""
fullnameOverride: ""

podLabels: {}

service:
  type: ClusterIP
  port: 3000

env:
  # This IP is the public IP of the Application Gateway
  - name: REACT_APP_BUG_SERVICE_URL
    value: "http://13.95.1.131/bugservice"

  # This IP is the public IP of the Application Gateway
  - name: REACT_APP_USER_SERVICE_URL
    value: "http://13.95.1.131/userservice"

ingress:
  className: "azure-application-gateway"
  annotations: {}
  path: "/"
  pathType: "Exact"
