base-microservice:
  replicaCount: 1

  image:
    repository: kriat/userservice
    pullPolicy: IfNotPresent
    tag: "latest"

  nameOverride: "userservice"
  fullnameOverride: "userservice"

  podLabels: {}

  service:
    type: ClusterIP
    port: 8080

  ingress:
    className: "azure-application-gateway"
    annotations:
      appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    path: /userservice/*
    pathType: Prefix

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10

  env:
    - name: "ASPNETCORE_ENVIRONMENT"
      value: "Production"

    - name: "ConnectionStrings__DefaultConnection"
      valueFrom:
        secretKeyRef:
          name: aks-secret-provider-secret
          key: userservicedb-connection-string

  initContainers:
    - name: wait-for-rabbitmq
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;",
        ]

  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aks-secret-provider"

  volumeMounts:
    - name: secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true
