version: '3.8'
services:
  bugservice:
    build:
      context: backend/bugservice
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=bugtracker;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bugtracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
