version: '3.8'
services:
  bugservice:
    build:
      context: backend/bugservice
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=bugservicedb;Database=bugs;Username=postgres;Password=postgres
      - UserService__Url=http://userservice:8080
    depends_on:
      - bugservicedb
    networks:
      - app-network
    ports:
      - "8080:8080"

  userservice:
    build:
      context: backend/userservice
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=userservicedb;Database=users;Username=postgres;Password=postgres
    depends_on:
      - userservicedb
    networks:
      - app-network
    ports:
      - "8081:8080"

  userservicedb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data-userservice:/var/lib/postgresql/data
    networks:
      - app-network

  bugservicedb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bugs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data-bugservice:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data-bugservice:
  db-data-userservice:
