# This is a SecretProviderClass using user-assigned identity to access an Azure Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
 name: {{ .Release.Name }}
spec:
 provider: azure
 parameters:
   usePodIdentity: "false"
   useVMManagedIdentity: "true"
   userAssignedIdentityID: {{ .Values.connection.clientId | quote }}
   keyvaultName: {{ .Values.connection.vaultName | quote }}
   # expose vault secrets defined in values
   objects: |
    array:
       {{- range .Values.secrets }}
       - |
         objectName: {{ . }}
         objectType: secret
         objectVersion: ""
       {{- end }}
   tenantId: {{ .Values.connection.tenantId | quote }}
 secretObjects:  # reflect exposed objects in k8s Secret
  - secretName: {{ .Release.Name }}-secret
    type: Opaque 
    data:
     {{- range .Values.secrets }}
     - objectName: {{ . }}
       key: {{ . }}
     {{- end }}
     