apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: rabbitmq-amqp
      port: 5672
      targetPort: 5672

    - name: rabbitmq-http
      port: 15672
      targetPort: 15672
