name: Build Bug Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/bugservice/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/bugservice/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml
    with:
      path: 'backend/bugservice/src'
  
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker_push.yml
    with:
      context: 'backend/bugservice'
    secrets:
      user: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
