name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'backend/bugservice/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/bugservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore backend/bugservice/src

      - name: Build application
        run: dotnet build backend/bugservice/src
  
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend/bugservice
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bugservice:latest
