name: 'Bugtracker: Build and Test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/bugtracker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/bugtracker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18.x', '20.x']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
      working-directory: frontend/bugtracker

    - name: Build
      run: npm run build
      working-directory: frontend/bugtracker

    - name: Test
      run: npm test
      working-directory: frontend/bugtracker
  
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker_push.yml
    with:
      context: frontend/bugtracker
      repository: bugtracker
      tag: latest
    secrets:
      user: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
