name: Push to Docker Hub

on:
  workflow_call:
    inputs:
      context:
        type: string
        required: true
        description: 'Path to the Docker context to build and push'
      repository:
        type: string
        required: true
        description: 'Name of the repository to push the image to'
      tag:
        type: string
        required: true
        description: 'Tag to push the image with'
    secrets:
      user:
        required: true
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.user }}
          password: ${{ secrets.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ secrets.user }}/${{ inputs.repository }}:${{ inputs.tag }}