name: Dotnet Build

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
        description: 'Path to the project to build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.path }}

      - name: Build application
        run: dotnet build ${{ inputs.path }}