name: Build User Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/userservice/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/userservice/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml
    with:
      path: 'backend/userservice/src'

  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker_push.yml
    with:
      context: backend/userservice
      repository: userservice
      tag: latest
    secrets:
      user: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}